

import axios from 'axios';
import React, { useEffect, useState } from 'react';
import download from '../assets/download.png'
import Loader from '../components/Loader';

type PostProps={
    name:string,
    photo:string,
    prompt:string
}

type PostData={
    data:PostProps[]
}
const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState<PostData>();

  const [searchText, setSearchText] = useState('');
  const [searchTimeout, setSearchTimeout] = useState(null);
  const [searchedResults, setSearchedResults] = useState<PostProps[]>();

  const fetchPosts = async () => {
    setLoading(true);

    try {
      const response = await axios.get('http://localhost:3001/api/v1/post');

     setAllPosts(response.data);

    } catch (err) {
      alert(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPosts();
  }, []);

  const handleSearchChange = (e:any) => {

    setSearchText(e.target.value);

   
      setTimeout(() => {
        const searchResult = allPosts!.data.filter((item) => item.name.toLowerCase()
        .includes(searchText.toLowerCase()) || item.prompt.toLowerCase().includes(searchText.toLowerCase()));
        setSearchedResults(searchResult);
      }, 500)
    
  }

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px] text-start">The Community Showcase</h1>
        <p className="mt-2 text-[#666e75] text-[14px] max-w-[500px] text-start">Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
      </div>

      <div className="mt-16 flex flex-col">
           <label htmlFor="">Search</label>
           <input onChange={handleSearchChange}  className="bg-gray-50 border border-gray-300
               text-gray-900 text-sm rounded-lg focus:ring-[#4649ff] focus:border-[#4649ff]
               outline-none block w-full p-3" type="text" />
      </div>

      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-[#666e75] text-xl mb-3">
                Showing Resuls for <span className="text-[#222328]">{searchText}</span>:
              </h2>
            )}
           
          </>
        )}
          <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
        { !searchedResults?
            allPosts?.data.map(post=>{
                return(
                    <div className="rounded-xl group relative shadow-card hover:shadow-cardhover card">
                    <img
                      className="w-full h-auto object-cover rounded-xl"
                      src={post.photo}
                      alt={post.prompt}
                    />
                    <div className="group-hover:flex flex-col max-h-[94.5%] hidden absolute bottom-0 left-0 right-0 bg-[#10131f] m-2 p-4 rounded-md">
                      <p className="text-white text-sm overflow-y-auto prompt">{post.prompt}</p>
                
                      <div className="mt-5 flex justify-between items-center gap-2">
                        <div className="flex items-center gap-2">
                          <div className="w-7 h-7 rounded-full object-cover bg-green-700 flex justify-center items-center text-white text-xs font-bold">{post.name[0]}</div>
                          <p className="text-white text-sm">{post.name}</p>
                        </div>
                        <button type="button"  className="outline-none bg-transparent border-none">
                          <img src={download} alt="download" className="w-6 h-6 object-contain invert" />
                        </button>
                      </div>
                    </div>
                  </div>
                )
            }):searchedResults?.map(post=>{
                return(
                    <div className="rounded-xl group relative shadow-card hover:shadow-cardhover card">
                    <img
                      className="w-full h-auto object-cover rounded-xl"
                      src={post.photo}
                      alt={post.prompt}
                    />
                    <div className="group-hover:flex flex-col max-h-[94.5%] hidden absolute bottom-0 left-0 right-0 bg-[#10131f] m-2 p-4 rounded-md">
                      <p className="text-white text-sm overflow-y-auto prompt">{post.prompt}</p>
                
                      <div className="mt-5 flex justify-between items-center gap-2">
                        <div className="flex items-center gap-2">
                          <div className="w-7 h-7 rounded-full object-cover bg-green-700 flex justify-center items-center text-white text-xs font-bold">{post.name[0]}</div>
                          <p className="text-white text-sm">{post.name}</p>
                        </div>
                        <button type="button"  className="outline-none bg-transparent border-none">
                          <img src={download} alt="download" className="w-6 h-6 object-contain invert" />
                        </button>
                      </div>
                    </div>
                  </div>
                )
            })
        }
        </div>
      </div>
    </section>
  );
};

export default Home;
